apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app.kubernetes.io/name: customer-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: customer-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app.kubernetes.io/name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: customer-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: customer-service
        app.kubernetes.io/instance: sad-markhor
    spec:
      containers:
        - name: customer-service
          image: "192.168.0.22:5000/spring-cloud-k8s-customer:1.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP